import { useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from "next/head";

export default function Home() {
  const router = useRouter();

  const shouldRedirect = true;

  useEffect(() => {
    if (shouldRedirect) {
      router.push('/').catch((error) => {
        console.error('Error occurred while redirecting:', error);
      });
    }
  }, [router, shouldRedirect]);

  return (
    <>
      <Head>
        <title>Pc Part picker v2</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <div className="container flex flex-col items-center justify-center gap-12 px-4 pb-16 pt-8">
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          PC <span className="text-[hsl(280,100%,70%)]">Part</span> Picker
        </h1>
      </div>

      </main>
    </>
  );
}
