import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { api } from "~/utils/api";
import { useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
    const router = useRouter();
    const { selected } = router.query;
    console.log(selected);

  return (
    <>
      <Head>
        <title>Pc Part picker v2</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <div className="container flex flex-col items-center justify-center gap-12 px-4 pb-16 pt-8">
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          PC <span className="text-[hsl(280,100%,70%)]">Part</span> Picker
        </h1>
      </div>

        <div className="text-slate-50"> 
          
<div className="relative overflow-x-auto shadow-md sm:rounded-lg pb-12">
    <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400 ">
        <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" className="px-6 py-3">
                    Component
                </th>
                <th scope="col" className="px-6 py-3">
                    Selection
                </th>
                <th scope="col" className="px-6 py-3">
                    Where
                </th>
                <th scope="col" className="px-6 py-3">
                    Price
                </th>
                <th scope="col" className="px-6 py-3">
                    <span className="sr-only">Buy</span>
                </th>
                <th scope="col" className="px-6 py-3">
                    <span className="sr-only">x</span>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <Link href="/component/gpu">
                    <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        GPU
                    </th>
                </Link>
                <td className="px-6 py-4">
                    i123
                </td>
                <td className="px-6 py-4">
                    Amazon
                </td>
                <td className="px-6 py-4">
                    $2999
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">Buy</a>
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium dark:text-red-500 hover:underline">X</a>
                </td>
            </tr>
            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                
                <Link href="/component/cpu"> 
                    <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        CPU
                    </th>
                </Link>
                <td className="px-6 py-4">
                    i7814
                </td>
                <td className="px-6 py-4">
                    Arvutitark
                </td>
                <td className="px-6 py-4">
                    $1999
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">Buy</a>
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium dark:text-red-500 hover:underline">X</a>
                </td>
            </tr>
            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    CPU Cooler
                </th>
                <td className="px-6 py-4">
                    asdsad
                </td>
                <td className="px-6 py-4">
                    Arvutitark
                </td>
                <td className="px-6 py-4">
                    $1999
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">Buy</a>
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium dark:text-red-500 hover:underline">X</a>
                </td>
            </tr>
            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    Case
                </th>
                <td className="px-6 py-4">
                    i7814
                </td>
                <td className="px-6 py-4">
                    Arvutitark
                </td>
                <td className="px-6 py-4">
                    $1999
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">Buy</a>
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium dark:text-red-500 hover:underline">X</a>
                </td>
            </tr>
            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    Memory
                </th>
                <td className="px-6 py-4">
                    i7814
                </td>
                <td className="px-6 py-4">
                    Arvutitark
                </td>
                <td className="px-6 py-4">
                    $1999
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">Buy</a>
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium dark:text-red-500 hover:underline">X</a>
                </td>
            </tr>
            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    Storage
                </th>
                <td className="px-6 py-4">
                    i7814
                </td>
                <td className="px-6 py-4">
                    Arvutitark
                </td>
                <td className="px-6 py-4">
                    $1999
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">Buy</a>
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium dark:text-red-500 hover:underline">X</a>
                </td>
            </tr>
            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    PSU
                </th>
                <td className="px-6 py-4">
                    i7814
                </td>
                <td className="px-6 py-4">
                    Arvutitark
                </td>
                <td className="px-6 py-4">
                    $1999
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">Buy</a>
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium dark:text-red-500 hover:underline">X</a>
                </td>
            </tr>
            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    Motherboard
                </th>
                <td className="px-6 py-4">
                    i7814
                </td>
                <td className="px-6 py-4">
                    Arvutitark
                </td>
                <td className="px-6 py-4">
                    $1999
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">Buy</a>
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium dark:text-red-500 hover:underline">X</a>
                </td>
            </tr>
            <tr className="bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-600">
                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    Monitor
                </th>
                <td className="px-6 py-4">
                    500W psu
                </td>
                <td className="px-6 py-4">
                    1a
                </td>
                <td className="px-6 py-4">
                    $99
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">Buy</a>
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium dark:text-red-500 hover:underline">X</a>
                </td>
            </tr>
            <tr className="text-xs border-t text-gray-700  uppercase bg-gray-50 dark:bg-gray-800 dark:text-gray-400">
                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    
                </th>
                <td className="px-6 py-4">
                    
                </td>
                <td className="px-6 py-4">
                    
                </td>
                <td className="px-6 py-4">
                    total sum
                </td>
                <td className="px-6 py-4 text-right">
                </td>
                <td className="px-6 py-4 text-right">
                    <a href="#" className="font-medium dark:text-red-500 hover:underline"></a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

          
        </div>
      </main>
    </>
  );
}
